import type { NextPage } from 'next'
import Head from 'next/head'
import Image from '../components/image/Image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>IS THIS THE MAX</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.background}>
        <div className={styles.blur}></div>
        <div className={styles.box}>
          <Image></Image>
        </div>
      </div>
      
    </div>
  )
}

export default Home
