import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const [value, setValue] = useState([0])
  return (
    <div className={styles.container}>
      <Head>
        <title>IS THIS THE MAX</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="story/greece">Greece!</Link>
    </div>
  )
}

export default Home
