import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>IS THIS THE MAX</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p className={`${styles.line1} ${styles.animTypewriter}`}>
        Happy Birthday Alex!
      </p>
      <span className={`${styles.button} ${styles.left}`}>
        <Link href="story/greece">Give me photos!</Link>
      </span>
      <span className={`${styles.button} ${styles.right}`}>
        <Link href="music">Give me music!</Link>
      </span>
    </div>
  )
}

export default Home
