import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const [value, setValue] = useState([0])
  return (
    <div className={styles.container}>
      <Head>
        <title>IS THIS THE MAX</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p className={`${styles.line1} ${styles.animTypewriter}`}>
        Happy Birthday Alex!
      </p>
      <div className={`${styles.button} ${styles.left}`}>
        <Link href="story/greece">Give me photos!</Link>
      </div>
      <div className={`${styles.button} ${styles.right}`}>
        <Link href="music">Give me music!</Link>
      </div>
    </div>
  )
}

export default Home
